### ISSUE TITLE
[TODO] 8월 단기목표

### ISSUE THREAD

**Issue by ch3224bin** [ch3224bin/vf_lifelog#1]
- [x] 다국어 처리
- [x] 진행중일때 입력한 내용 수정시 localStorage에 저장
- [x] 바탕화면 바로가기 아이콘 만들기
- [x] About 페이지 작성
